### PR TITLE
Release-specific docs

### PR DESCRIPTION
**Pull request by andrewdavidwong**

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
TestDeploy

**Comment by andrewdavidwong** [comment]
PipelineRetry

**Comment by andrewdavidwong** [comment]
PipelineRetry

**Comment by andrewdavidwong** [comment]
TestDeploy

**Comment by marmarek** [comment]
TestDeploy

**Comment by andrewdavidwong** [comment]
TestDeploy

**Comment by andrewdavidwong** [comment]
PipelineRetry

**Comment by andrewdavidwong** [comment]
@marmarek:
> What you can try, is to bump qubes-doc submodule in the other PR (in a separate commit), and deploy then. I'm not 100% sure it will work, but there is a chance.

Ok, I tried to do that here, but it looks like the site is no longer building, so there is nothing to deploy. I'm guessing this is due to the `_doc` merge conflict, which means that this won't work. Am I reading the situation accurately?

**Comment by andrewdavidwong** [comment]
Superseded by migration to RTD.

**Pull request closed without merging**
