### PR TITLE
Small change to Funding page

### PR DESCRIPTION
**Pull request by katsinger**
Changed a hyphen to an en dash. (Please disregard all of my test commits as I get the hang of this workflow.)

### CODE REVIEW

**Comment by jpouellet** [comment]
Please [squash your commits](https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit).

**Comment by katsinger** [comment]
@jpouellet, thanks for the link! I've given it a try but without 100% success in pushing it back up. I'm a first-time Git user and this is my first pull request. Hope you can bear with my baby steps. :baby: :footprints:

**Comment by jpouellet** [comment]
If the commits are squashed (you only see one commit by you in `git log`), and the commit contains what you intend it to contain (confirmed via `git show`) then try `git push --force`, or possibly `git push --force your_remote your_branch` (probably `git push --force origin master`).

Thanks for your contribution (regardless how small), and welcome to the community! :)

**Comment by jpouellet** [comment]
Alternately, if squashing is what you are having trouble with, the easiest way might be to just delete your local copy of the repo, re-clone it, and re-make your change in a single commit, and `git push --force` it.

May seem silly, I know, but we would prefer to avoid polluting the commit history of our master branch with intermediate commits without any net changes.

Also... https://xkcd.com/1597/ ;)

**Comment by andrewdavidwong** [comment]
@jpouellet: Just some context: Prior to this PR, we had an email discussion with @katsinger, who has generously agreed to help us with some content work for the site and who told us to expect a test PR after we explained our [contribution](https://www.qubes-os.org/doc/doc-guidelines/) procedure. Thank you for being helpful and welcoming her to the community. :)

@katsinger: As usual, @jpouellet has provided good advice. Since this was just a test PR to become familiar with our merging process, you can either try to squash your commits as he said, or simply delete this PR and submit a new one.

**Comment by jpouellet** [comment]
> Prior to this PR, we had an email discussion with @katsinger, who has generously agreed to help us with some content work for the site

Awesome! I can't speak for the project, but I think we all appreciate all the help we can get :)

**Comment by katsinger** [comment]
Thanks again for your help, @jpouellet! I definitely need it!

@andrewdavidwong, cross fingers that I can get it all worked out!

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong, cross fingers that I can get it all worked out!

If you need any help, just let us know!

**Pull request closed without merging**
