### PR TITLE
Make the Qubes OS downloads page fully data driven and beautiful

### PR DESCRIPTION
**Pull request by Rudd-O**
I've moved everything that was text and Markdown into the data file.

I've also taken the liberty of making sure that we have a stunning download page, which takes the user step-by-step through the process, from getting the image to the moment the OS is running on his computer.

I'm not expecting this to be merged "as-is", rather I expect this to generate review improvement requests from you, and then we will be able to merge it.

If you want to see how it looks, launch jekyll serve on a checkout of this branch.  I assure you, you will be shocked.

### CODE REVIEW

**Comment by Rudd-O** [comment]
Please help me figure out what to do with the mother fucking CSS :-D

**Comment by bnvk** [comment]
No problem! I will looking into this! I'd assign myself to the issue, but I don't have access to doing so!

**Comment by axon-qubes** [comment]
Wow, great work so far!

**Comment by Rudd-O** [comment]
How is the review of this going?  I'd really like to see this go in soon.

**Comment by Rudd-O** [comment]
Ping.

**Comment by marmarek** [comment]
@bnvk any opinion here?

I like the table layout, but some details needs to be worked out - for example the title is "Live, experimental and older releases" - then, the third option is "Qubes Release 3.0 (latest stable release)", which doesn't qualify to any of those. I think it should be named like "All download options" or sth like this. Also the obsolete warning should be somehow more emphasized.

What currently is broken, is top of that page - all the buttons are in one narrow (but long) column.
Also not sure about the content of top of this page. Currently we have "Before you download..." section, which indeed isn't great, but have some useful information - for example system requirements and hardware compatibility list. In new layout it is somehow put later in that page.
Also not sure if alternative location (ftp.qubes-os.org vs mirrors.kernel.org) should be really promoted at the top of that page. IMHO there should be just one download button, then a link to a section with all the options (which you've currently named "Pick a live, experimental or older release").

**Comment by Rudd-O** [comment]
OK, here are my thoughts.

I agree that we should probably move out the featured stable release out of "experimental, live and older releases", because it's obviously not that.

I am interested in learning how you would like me to emphasize the warning.  Happy to hear ideas on it.

I don't understand the "broken is top of that page" comment, screenshot please?  It doesn't appear that way here.

I'd rather not put the "Before you download" section before the download.  We want people to get the software -- that should be the single and most prominent focus of the page, and therefore the first and largest one -- and IF they have any questions, read about them in a separate section which is duly noted.

One download button and "more options" sounds interesting, but we do want people to have -- right there exactly where their eyes land at first -- the secondary options to download it from BitTorrent (much faster) or from the upstream server qubes-os.org.  In my view, it would be not nice to the user to demand they skip to a different part of the page in order to do so, because it breaks the 1 2 3 4 step flow.

Ideally, we would A/B test this version and the proposal you're advancing.  But I don't know how to go about doing that.

**Comment by marmarek** [comment]
> I am interested in learning how you would like me to emphasize the warning. Happy to hear ideas on it.

Bold?

> I don't understand the "broken is top of that page" comment, screenshot please? It doesn't appear that way here.

new-downloads-buttons1

new-downloads-buttons2

> I'd rather not put the "Before you download" section before the download.

It may not be exactly "before" that download button. But somewhere near it, visible without scrolling.

> One download button and "more options" sounds interesting, but we do want people to have -- right there exactly where their eyes land at first -- the secondary options to download it from BitTorrent (much faster) or from the upstream server qubes-os.org. In my view, it would be not nice to the user to demand they skip to a different part of the page in order to do so, because it breaks the 1 2 3 4 step flow.

Generally *forcing* user to make a choice isn't a good idea. But also making it unnecessary hard to to apply the choice user have already made is bad. We want the download page to be easy: if user desire is to "download Qubes OS" it should be obvious what to do ("click this big download button", not "oh, there are 3 releases, each of them have 4 download options, I'm lost"). But also if user desire is to "download Qubes OS using BitTorrrent" it should be easy. I think "other download options" is a good compromise (as long as there is such link, not manual scrolling through a long page).

> Finally, I would advise not letting the perfect be the enemy of the good. There are certainly improvements to be made, important improvements, but perhaps we can address those incrementally after we have gotten the first iteration out. Release early release often.

Yes, IMHO the only real blocker is that button layout visible on screenshots.

**Comment by Rudd-O** [comment]
I don't see anything broken on the screenshots.  The way it renders is how it's meant to be rendered.

Ordinarily, there *would* be an option for BitTorrent download of the featured release at the top of the page -- it would be a separate secondary (white) button to the right of "Via HTTPS from ftp.qubes-os.org" in the first section "GET QUBES OS".  But we haven't produced a BitTorrent option for 3.0 stable, and that is the simple reason why it does not appear.  Otherwise you would see two secondary buttons.   If you would like to see how it looks like when there's a BitTorrent option, change the featured release (in the data file) to be the release name of the 3.1 release that has a torrent file.  Then you'll see how it looks like with the BitTorrent Option.

The intention behind the BIG BLUE button and the secondary white buttons is to present to the user the most commonly-chosen option so he doesn't have to think about it.  BUT, if he would rather use a different option, they are right there.  No need to scroll, no need to jump to a different part of the page (which could cause him to miss the rest of the steps, because people forget and short attention spans are a problem), if user wants BitTorrent, user should be able to click the BitTorrent link right there.

My intention is that the user be able to do everything about Qubes OS without needing to scroll too much, or see an overwhelmingly complex list of things (how it was before).

Obviously, the option to hide the featured release from the list of older / experimental releases, is something I have to look into and fix.  And, naturally, the way the blue links line up also bothers me quite a bit.  The only link I believe belongs there, is the link "how to upgrade to 3.0", which could help existing users save a few gigabytes of bandwidth.  The other stuff belongs somewhere else.

I believe the entire "before you download" section was wrongly conceived from the start.  First of all, it was just a mostly random collection of information, some of which is important but was being showed at an inopportune time in the workflow, and some of which is frankly unimportant and most people just skip it (I know I did).  I think the *correct* way to organize and deliver the *necessary* information must be rethought from the ground up, in such a way that it doesn't appear as a roadblock to the new user, *but* also isn't easily-missed (otherwise you get unnecessary emails sent to the mailing list).

**Comment by Rudd-O** [comment]
I have addressed most of your comments in a version of the page that looks substantially different, hopefully better.  The featured release no longer appears in the bottom experimental and older release list.

**Comment by Rudd-O** [comment]
As a bonus, now no scrolling whatsoever is required to read all steps.

**Comment by marmarek** [comment]
It's slightly better now. I think the current release should be included in full table below, just its title needs to be adjusted.

Now it looks like this:
new-downloads-buttons3

@bnvk any opinion?

**Comment by Rudd-O** [comment]
All the information of the current release is included in the first "DOWNLOAD" chunk as well as the second "VERIFY" chunk.  I don't think we need to repeat ourselves.  If, however, we must, then the work to do that is very trivial.

**Comment by bnvk** [comment]
Sorry for my delayed feedback, I've been really sick all last week. I'm glad to see good progress has been made, thanks @Rudd-O  :)

That said, there's a handful of things I want to change in this, do you want my notes here, or should I just do them myself?

**Comment by marmarek** [comment]
If you could handle this to the end @bnvk , that would be great. Thanks! :)

**Comment by Rudd-O** [comment]
Notes here would be preferable, but patches on top of my patches along with the notes would be even BETTER.

**Comment by Rudd-O** [comment]
Get better soon @bnvk !

**Comment by Rudd-O** [comment]
Ping @bnvk :-)

**Comment by Rudd-O** [comment]
(Merging conflicts now...)

**Comment by marmarek** [comment]
To speed things up, @bnvk do you think @Rudd-O's page (without your adjustments) is worse than the current one? If not, I think we can merge it just now, and improve later.
For your convenience there is a screenshot above.

**Comment by bnvk** [comment]
@marmarek just sent a pull-req with enough improvements to @Rudd-O work to merge now!

**Comment by marmarek** [comment]
Thanks @bnvk and @Rudd-O !

**Comment by Rudd-O** [comment]
@bnvk @marmarek I don't know what happened, but the page looks **horrible** and the semantic meaning of it is **gone**.  I know I am not a graphic design professional, nor am I a copy editor, but judging from the results, I can spot at least these flaws in what went in:

* The buttons aren't the same width (looking horribly misaligned).
* The spacing between the buttons is gone, the repetition "Download now" makes the download page look like a pirate site with DOWNLOAD NOW clickbait ads.
* The buttons are no longer centered either.
* The lists are not even aligned with the buttons anymore.
* The last step -- Enjoy -- is totally gone.
* All of the carefully-chosen wording that I had thought, for **hours**, has been replaced with tech-speak.  "Download ISO" (false in at least one case).  "Verify Your Download".
* The height of each column is obscenely tall, and disproportionate / unbalanced between columns.

Worst of all, **none of these aesthetically horrible changes went through review.**  I could have been asked *why* did you do X thing in Y way, and what's the rationale, and what not.  I wasn't really consulted after all the work I put in.

It feels pretty demeaning, to be honest.  It is as if none of the details I had put *days* of work into, had been considered.  You know, maybe my work was shit, but even if that was the case, I'm terribly disappointed with how this was handled, both with how dreadfully long it took, and what the end result was.  Very discouraging.

In the future, you will need to hire professionals like a graphic designer or a copy editor to fix the communications and visual trust problems I attempted to fix, which the page as committed does not (makes them worse).

I probably will not be contributing more improvements to the Web site again.

**Comment by marmarek** [comment]
Hmm, really strange, on my local copy it looks much better. Some missing CSS or sth?

Oh, I see - it looks good **only in narrow layout** (when steps are each under another, not in a single row). Probably because now there are three buttons to download (ftp.qubes-os.org, mirrors.kernel.org and torrent).

Temporary disabled one of HTTPS downloads to workaround the problem.

> EDIT: it appears that the basis for the commit that ended up merged, was an old commit of mine in the same branch (I had updated the branch to be a single commit, and I recognize the old commit names merged here). That is probably the consequence of a git pull or git rebase missing somewhere.

I've especially merged @bnvk changes over your latest version to prevent such problem.

**Comment by bnvk** [comment]
@Rudd-O there is merit to some of your comments, thank you for taking time to communicate them!

When I was working locally, there was only 2 downloads of 3.1... I didn't think we had the Torrent file ready and wanted to push *something* up. In the merging (like you said) something must not have rebased correctly, as a few `<hr>` and other things were missing and it does not look as I had intended.

This page is still a work-in-progress. There is a few points that inform the changes I made vs. where you were taking things. I really liked the "Enjoy" step, but this isn't the right page for that. I plan to re-add that elsewhere. I elaborated more on this in #1833

That said, there is a certain experience I am slowly working Qubes towards- one aimed at being accessible to non-technical users. I just finished drafting up a [usability & UX guide](https://www.qubes-os.org/doc/usability-ux/) that describes UI / UX steps towards this goal.

> It feels pretty demeaning, to be honest. It is as if none of the details I had put days of work into, including all the successful and prominent download pages from other products that I had researched, had been considered. Maybe my work was shit to begin with, but even if that was the case, I'm terribly disappointed with how this was handled, both with how dreadfully long it took, and what the end result was. Very discouraging.

I'm sorry you feel that way. A lot of the work you did with creating the `downloads.yml` file and the Jekyll logic in the page was *very* much appreciated and is still in the codebase. Your work was not "shit to begin with" it's just in the future we need to have better dialogue about goals / direction before spending days of time wasted for all parties involved. I hope you are up for more contributions, and I'm happy to try better next time. FWIW, I prefer and believe there are significant merits to using real-time chat (IRC or Jabber) to achieve better understanding and collaborations of this sort.

@axon-qubes @marmarek we should chat in an email thread about how to better coordinate stuff like this and #1833

**Comment by axon-qubes** [comment]
> we should chat in an email thread about how to better coordinate stuff like this and QubesOS/qubes-issues#1833

Let's have those discussions in their respective GH issues, unless something needs to be confidential for some reason.

**Pull request merged**
