### PR TITLE
Donate and Partners pages entirely rewritten

### PR DESCRIPTION
**Pull request by katsinger**
The content of the Donate and Partners pages has been rewritten from a communications standpoint to

- address the needs of the target audience
- provide a better information UX
- clarify the donation options
- simplify the donation process for potential donors.

The purpose of separate Funding and Partner pages was unclear and confusing. To remedy this, the information on the Funding page has been folded into the Donate and Partners pages and should therefore be removed.

### CODE REVIEW

**Comment by jpouellet** [comment]
Thanks for working on this.

Unfortunately your git usage got a little... well... it appears it could use some assistance.

Would you like help resolving your git issues (picking up where we left off with https://github.com/QubesOS/qubesos.github.io/pull/91)? Or I could just cherry-pick the good commits, submit them as a separate PR, and you could re-clone for future changes. Whatever you prefer.

[Obligatory XKCD](https://xkcd.com/1597/) :)

**Comment by katsinger** [comment]
Ugh... Yes, I would love some help, @jpouellet! Thanks so much for reaching out!

Ideally I'd have this resolved before Friday noon, and I only have mornings to work on this. What do you think? Possible? Let me know how I should proceed.

**Comment by katsinger** [comment]
@andrewdavidwong, how would you like me to proceed so we can get my suggestions reviewed and implemented?

**Comment by jpouellet** [comment]
@katsinger oops, sorry for leaving you hanging.

I think the easiest thing would be to:
1. make a new clone of the git repository
2. copy over only the changes you intended to make (e.g. by replacing the intended files in the new clone with your final changed copy taken from your current clone)
3. make a single commit containing those changes
4. make a new pull request with that single commit

If you don't care about git and would rather spend your time working on the actual content, I'm happy to do that for you.

It is certainly possible to fix the current state of your repo instead of re-cloning, but to do so without lots of back and forth instructions would likely require either being at the same computer or spending a bunch of time reading git docs.

In case you do want to try to do that, it would involve removing the file you've added somehow containing the whole git history (named "df" followed by some special chars), committing that, and squashing your commits to hide the incremental changes (test, test, test, derp, remove deep, etc.), and then using push --force to overwrite the changes for this PR.

**Comment by katsinger** [comment]
@jpouellet, no worries! I would love nothing more than to rise to the occasion and implement this myself, but I think I'll just cause myself unnecessary headaches.

So yes, please do this part for me! Thank you, thank you!

**Comment by jpouellet** [comment]
Done here: https://github.com/QubesOS/qubesos.github.io/pull/109

**Pull request closed without merging**
