### PR TITLE
Translation prepare

### PR DESCRIPTION
**Pull request by marmarek**
This is the massive refactor of the main website repository done by @maiska (https://github.com/marmarek/qubesos.github.io/pull/5) but with clean git history. Plus a few fixups. The actual translation tools are not added here yet and the language switcher menu is disabled. 
There should be no visual change in the output - I've checked this on a few pages of different types and it seems to be ok.
Merging this now would greatly ease the work on finishing actual translations integration, as we can avoid frequent merge/rebase and conflict resolution.

Thanks @maiska for this work!

### CODE REVIEW

**Comment by marmarek** [comment]
PipelineRetry

**Comment by andrewdavidwong** [comment]
It looks like some of the new code inconsistently uses spaces and tabs for indentation. :frowning_face: 

Since the existing codebase uses all spaces, no tabs should be introduced.

**Comment by andrewdavidwong** [comment]
I'm seeing some small bugs:

 - `<` character on its own line at the start of the body text of each News post
 - Half of the links at the top of the Team page now have blue text
 - Scope of the "unsupported" link covers more text in alerts on the Download page

I don't have time to look through every page of the website, of course, but these are the ones I've noticed so far.

I'm also confused about the restructuring. For example, this large file is introduced: https://github.com/QubesOS/qubesos.github.io/blob/9c345c7faf97089415f612bc5e7a7198d4c8b3fb/_data/index.yml

But we still have `doc.md`. That seems like bad duplication. What happens when we add/remove/rename a document? Surely we don't want to be maintaining both now. Does `index.yml` somehow get auto-updated?

**Comment by marmarek** [comment]
> For example, this large file is introduced: https://github.com/QubesOS/qubesos.github.io/blob/9c345c7faf97089415f612bc5e7a7198d4c8b3fb/_data/index.yml
> 
> But we still have `doc.md`

I have not changed qubes-doc repo here at all, but I think the doc.md is not used here anymore. The matching PR for qubes-doc (https://github.com/marmarek/qubes-doc/pull/3) removes the doc.md file. TBH, I'd prefer for this indeed be auto-generated, which I think your release-specific split does.

> Scope of the "unsupported" link covers more text in alerts on the Download page

Same for "testing". I've noticed it too. Technically it's trivial to fix, but it will make translation harder, because it will split [that sentence](https://github.com/QubesOS/qubesos.github.io/blob/9c345c7faf97089415f612bc5e7a7198d4c8b3fb/_data/download.yml#L120) into two parts (one for link and one without). IMO linking from the whole sentence is a good compromise.

**Comment by marmarek** [comment]
testdeploy

**Comment by andrewdavidwong** [comment]
> > For example, this large file is introduced: https://github.com/QubesOS/qubesos.github.io/blob/9c345c7faf97089415f612bc5e7a7198d4c8b3fb/_data/index.yml
> 
> > 
> 
> > But we still have `doc.md`
> 
> 
> 
> I have not changed qubes-doc repo here at all, but I think the doc.md is not used here anymore. The matching PR for qubes-doc (https://github.com/marmarek/qubes-doc/pull/3) removes the doc.md file. TBH, I'd prefer for this indeed be auto-generated, which I think your release-specific split does.
> 

That would be fine too, as long as we're not trying to manually keep two or more files in sync. 

> 
> > Scope of the "unsupported" link covers more text in alerts on the Download page
> 
> 
> 
> Same for "testing". I've noticed it too. Technically it's trivial to fix, but it will make translation harder, because it will split [that sentence](https://github.com/QubesOS/qubesos.github.io/blob/9c345c7faf97089415f612bc5e7a7198d4c8b3fb/_data/download.yml#L120) into two parts (one for link and one without). IMO linking from the whole sentence is a good compromise.

Ok, that's fine then.

**Comment by marmarek** [comment]
testdeploy

**Comment by marmarek** [comment]
@andrewdavidwong I've fixed the issues per the above discussion.

**Pull request merged**
