### PR TITLE
Create Jobs page (QubesOS/qubes-issues#1700)

### PR DESCRIPTION
**Pull request by andrewdavidwong**
CC: @mfc, @bnvk, @marmarek

### CODE REVIEW

**Comment by marmarek** [comment]
Generally it's ok. But there is one problem: if we call it "jobs", it implies (at least in my understanding) some salary. And being somehow short on funding, we can't provide it right now. So either I would change the title, or add some disclaimer.

**Comment by axon-qubes** [comment]
Oh, I thought this was a page for advertising paid positions.

**Comment by marmarek** [comment]
Yes, it would be, when we manage to get more funding.

**Comment by axon-qubes** [comment]
Changed "jobs" to "join" (and removed "hiring"), but maybe someone else has a better idea about how to present it.

**Comment by mfc** [comment]
looks great! thanks for drafting and modifying per marek's request. maybe it can be "join us", it can be a button on the Team page as well as elsewhere. cc/ @bnvk

**Pull request merged**
