### PR TITLE
Update website for survey

### PR DESCRIPTION
**Pull request by andrewdavidwong**
Updates requested in https://github.com/QubesOS/qubes-issues/issues/5732.

CC: @ninavizz, @marmarta

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
@ninavizz, could you confirm these changes? In particular, no URL was specified for the "Begin Survey" button, so I used the URL from the tweet.

**Comment by ninavizz** [comment]
Looks good from what I can tell by just eyeballing the code! TY for whipping this out so quick, excited!

**Comment by andrewdavidwong** [comment]
@ninavizz, do we want to merge right now, or are we waiting for other balls in the air?

**Comment by ninavizz** [comment]
@andrewdavidwong As long as it visually "looks" good to you per what the mockup suggested, go ahead and merge!! :)

**Pull request merged**
