### PR TITLE
Add unikernel details

### PR DESCRIPTION
**Pull request by jpouellet**

### CODE REVIEW

**Comment by marmarek** [comment]
@talex5 what do you think? Would you like to be a mentor for this project?

**Comment by talex5** [comment]
Yes, I'd be happy to mentor someone to update mirage-firewall so that it "supports all the networking-related functionality as the default sys-firewall VM, including configuration via Qubes Manager".

You'll probably want a second mentor for the Qubes project side, as the work will also likely involve changing the firewall configuration format (which is currently Linux-specific), adjusting the dom0 tooling, and getting the work integrated in Qubes - areas I'm not familiar with.

/cc @yomimono (who wrote the mirage-nat library, maintains the Mirage tcpip/stack, and has recently added a qubes target to the mirage configuration tool)

**Comment by talex5** [comment]
Might be worth linking to <https://groups.google.com/forum/#!msg/qubes-devel/kvbKXT5CJMU/rSMD6Je3BgAJ> as well.

**Comment by marmarek** [comment]
> You'll probably want a second mentor for the Qubes project side, as the work will also likely involve changing the firewall configuration format (which is currently Linux-specific), adjusting the dom0 tooling, and getting the work integrated in Qubes - areas I'm not familiar with.

Actually this part had some progress - new format already defined and implemented (Qubes 4.0): https://www.qubes-os.org/doc/vm-interface/#firewall-rules-in-4x
Anyway, yes - that other mentor would be me.

**Pull request merged**
