### PR TITLE
Endorsements update

### PR DESCRIPTION
**Pull request by andrewdavidwong**
CC: @rootkovska, @mfc

### CODE REVIEW

**Comment by mfc** [comment]
we can't just add more and more endorsements to that area of the homepage. needs to be few and powerful. maybe have a separate page for more. so let's update snowden, keep others out for now (unless we think they are better than the ones already there).

**Comment by andrewdavidwong** [comment]
I agree that there shouldn't be too many of these on the front page, but it's not obvious to me that six is too many.

**Comment by rootkovska** [comment]
On Sun, Oct 02, 2016 at 04:54:26PM -0700, Andrew David Wong wrote:
> I agree that there shouldn't be too many of these on the front page, but it's not obvious to me that six is too many.
> 

Ok, I agree with Micheal. I think 6 might be too much indeed, and we should keep
it at 4. It seems that 4 is an "industry standard" now:
https://whispersystems.org/

We should also move Snowden's endorsement as the first. If for nothing else,
than because he represents the single most high profile target among all the
endorsers we have.

joanna.

**Comment by rootkovska** [comment]
Also, since Isis' image is publicly known [1] (and with her approval [2]), I believe we should update the icon next to her endorsement to be more meaningful. I will ask her additionally if she's ok and if she has a preferred image.

[1] https://www.youtube.com/watch?v=xGIE7KTJiBY
[2] https://twitter.com/isislovecruft/status/730239562711216128

**Comment by mfc** [comment]
for the snowden quote I would shorten it to "If you're serious about security, Qubes OS is the best OS available today." *or* "If you're serious about security, Qubes OS is the best OS available today. It's what I use, and free."

if it's possible we can try to keep (add) the Soghoian quote, as I think it is quite good, but we don't want to overdo the homepage.

I would not add the Todd quote, I feel it's not clearly understandable to newcomers and we don't want so many endorsements on the homepage. If we were to use it, I would significantly shorten it to: "your standards get higher w/ Qubes OS".

re: Isis image, you will have to ask her.

**Comment by andrewdavidwong** [comment]
@rootkovska: Do you agree about shortening the new Snowden quotation?

@mfc, @rootkovska: Which one should be dropped (if any) in favor of Soghoian's?

**Comment by rootkovska** [comment]
I think we have enough real estate to include the whole Snowden quotation.

**Comment by mfc** [comment]
it's not a real estate question, it's an impact question. the last sentence doesn't add anything to a newcomer -- from the first sentence we already know Qubes is serious about security.

**Comment by andrewdavidwong** [comment]
How's this?

**Comment by rootkovska** [comment]
We definitely want to keep the Micah's endorsement.

**Comment by andrewdavidwong** [comment]
Ok. Which of the other two would you like to drop?

**Comment by mfc** [comment]
I would drop djb, to: Snowden, Micah, Isis, Soghoian

**Comment by rootkovska** [comment]
We should not drop djb, since he's probably the most technical expert in this group.

**Comment by mfc** [comment]
let's try five then and see how it looks.

**Comment by rootkovska** [comment]
Looking at the problem form the perspective of what types of audience would be influenced by each, I think that perhaps (Micah + Snowden) pretty much address the same audience as Chris. Am I mistaken? Thus, because we definitely don't want to drop Micah (he has been the longest and most vocal Qubes evangelist we have had AFAIK), neither Snowden (there are few people out there who have outsmarted the nation superpower and who gave us an endorsement), this means we should drop Chris. Sorry, Chris :)

**Comment by mfc** [comment]
okay sounds like we're back to where we've started, but with an updated Snowden quote. I think that's fine for now.

I think once we have separate "pitch" pages for different audiences we can include additional quotes from each community.

**Comment by andrewdavidwong** [comment]
How's this?

**Comment by andrewdavidwong** [comment]
Merged. The only thing left is to request an updated photo from Isis, if you still want to do that, @rootkovska.

**Comment by mfc** [comment]
great, thanks!

**Pull request merged**
