### PR TITLE
Website: (Re-)Include site-wide variables only where necessary

### PR DESCRIPTION
**Pull request by tokideveloper**
Fixes QubesOS/qubes-issues#6734

### CODE REVIEW

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
TestDeploy

**Comment by marmarek** [comment]
TestDeploy

**Comment by marmarek** [comment]
TestDeploy

**Comment by marmarek** [comment]
TestDeploy

**Comment by marmarek** [comment]
TestDeploy

**Comment by marmarek** [comment]
(in context of  https://github.com/QubesOS/qubes-issues/issues/6747) @andrewdavidwong I can mark the deployment as failed, but setting actual failure reason doesn't work for some reason. Still, I think that's an improvement in the feedback here.

**Comment by andrewdavidwong** [comment]
> (in context of  https://github.com/QubesOS/qubes-issues/issues/6747) @andrewdavidwong I can mark the deployment as failed, but setting actual failure reason doesn't work for some reason. Still, I think that's an improvement in the feedback here.

It is. Thanks!

**Review by marmarek — APPROVED** [review]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Approved as of 4bf20cde11abbf1edc4786f4be2d35818c62ba0a
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEnYWYU8Ll1fIX9iss8yiUvpaEk4oFAmDjpy8ACgkQ8yiUvpaE
k4rpuxAAr8KxOPPtQYJMC9IzHE7hc1mz5StHAu/QwgbhKTtama/IRF3mAqwrQmHS
5wGyF2nmQxcQI7nowbuN9JlqtGZzK1qHt2Qv0ONo/OVSfk+5GHyNkotkAGyMXuo7
2+4H5SuEoQ+33KuyLFJd/pKKuTAxUuUXQQEo4iEJzzJRZU3+wb4PmxJJfp7l8GFC
lAxGQHiTU0JUpbLUoNkLPBnlwFmjUJkYwguO/ip4OHcMSha/EJfSq1KRoPwp2U6H
lC7DgN3sI04pQ5576Ih9VoKXRhefK9aXkHST2/ZB1S4r62j5z3aFSSil+CJjlCVa
ooR38Ta+b6QwPF8cGigUxQqKqmbwyfkl7TkUvles0GGLx0LXXQiOVlNl8d+cgS2f
dJQpFhtALQFszRpTD830rPoUCZRr75Y6AW5c0AsSa8V5bHVBr8rpc1OKRJKmLH/6
8XqrAzceqgyTzF4o26W3wi2Mn4tCtJrQcBKCx6Rr1IFjU2JVnBnGacioMfimdJ9y
Z8Oq+bNEuKdbvUslYAyZ2L8pvyth2XBNCMhL4v+8vSy6INzeVHNCm/Sf0lPK39TK
JIWXxutgld5MKUjmAyqCYK+qGGF6HCIT6Rs9+mclG5LukWOJRJFb2CrWSNsMZbCM
wUkOm0AdCSAoFgG7QQTv6EYzKaYzqY6UkZLYKhAgzcX62X6gmwI=
=CSHe
-----END PGP SIGNATURE-----
```

**Comment by andrewdavidwong** [comment]
Unfortunately, merging this PR has resulted in this:

screenshot-localhost_4000-2021 07 06-04_00_06

**Comment by andrewdavidwong** [comment]
Reverted: https://github.com/QubesOS/qubesos.github.io/commit/82f510da0527aeb46c17a83719799fdc22633921

**Comment by andrewdavidwong** [comment]
I think it's because the comment lines that are indented by four spaces are being interpreted as a code block.

**Comment by andrewdavidwong** [comment]
Original commit reapplied and fixed by unindenting comments: https://github.com/QubesOS/qubesos.github.io/commit/03a7cff26cbb19da3e5db4af487b22d84e377a68

All good now.

**Comment by tokideveloper** [comment]
Thanks for finding and fixing the bug! It seems that I didn't test it thoroughly enough.

**Pull request merged**
