### PR TITLE
move video, screenshots, to top of Intro page

### PR DESCRIPTION
**Pull request by mfc**
so if folks want visuals they don't have to go through an entire page of text to get to them.

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
There have to be better ways to do this. Doing it this way doesn't really make sense, because now the "Getting Started" link is above the Intro text, which inverts the logical order of information presentation. Someone who doesn't even know what Qubes OS *is* yet shouldn't be presented with a post-installation guide prior to being provided with an explanation of what it is.

Please feel free to resubmit a change that handles this in a better way.

**Comment by andrewdavidwong** [comment]
(Also, you have unnecessary whitespace and a horizontal rule above the row of three links.)

**Comment by mfc** [comment]
agreed. maybe pull the first two sections to be up top, and then keep Getting Started at the bottom? anyway the page needs something, but this wasn't it.

**Comment by andrewdavidwong** [comment]
@mfc: What do you think that? I just added buttons for Video Tours and Screenshots to the top.

**Comment by mfc** [comment]
looks great, thanks!

**Pull request closed without merging**
