### PR TITLE
Make HCL tables sortable

### PR DESCRIPTION
**Pull request by andrewdavidwong**
Uses sorttable, by Stuart Langridge, under the X11 License:
https://kryogenix.org/code/browser/sorttable/

See QubesOS/qubes-issues#3795 for discussion.

### CODE REVIEW

**Comment by marmarek** [comment]
testdeploy

**Comment by marmarek** [comment]
@andrewdavidwong with new CI, I've added deploy feature - after CI completes, you can post "testdeploy" comment and the built version is deployed under wwwpreview.qubes-os.org (linked in "view deployment").
There is a whitelist on which github users have this power, currently its you and me, but I'm find with adding more.
Multi-PR changes are not supported yet (like this one, requiring another PR in qubes-doc). That's why I pushed a commit updating _doc submodule here, to have it included in this test deployment.

As for the actual sorting, I think the issue is when a row is split for multiple versions - search for example for "Fujitsu S751" in the unsorted table.

**Comment by andrewdavidwong** [comment]
> with new CI, I've added deploy feature - after CI completes, you can post "testdeploy" comment and the built version is deployed under wwwpreview.qubes-os.org (linked in "view deployment").

Cool feature. Thank you!

> There is a whitelist on which github users have this power, currently its you and me, but I'm fine with adding more.
Multi-PR changes are not supported yet (like this one, requiring another PR in qubes-doc). That's why I pushed a commit updating _doc submodule here, to have it included in this test deployment.

Makes sense. No problem.

> As for the actual sorting, I think the issue is when a row is split for multiple versions - search for example for "Fujitsu S751" in the unsorted table.

Yeah, I figured it was something like that. I suppose it makes sense, thinking about the way that column would be sorted. So, we either need to forbid rows-within-rows or find some sorting method that keeps them together.

**Comment by marmarek** [comment]
The testdeploy feature should also work in the qubes-doc repo, but I haven't tested it there yet.

**Comment by lubellier** [comment]
Is something blocking this PR? No changes since 5 months whereas it's a nice feature.

**Comment by andrewdavidwong** [comment]
> Is something blocking this PR? No changes since 5 months whereas it's a nice feature.

Yes, it is blocked on an unsolved problem. See above, including the linked issue. If you can help solve it, we'd welcome the help.

**Comment by lubellier** [comment]
I'm watching this blocked problem, I got the environment (podman, git branch) and I built the *hcl-sorttable* version of the website, and so I reproduced the sort problem.

I see that the problem is about **26** HCL yml files:
```
user@poder _hcl ((adw_9736641e))]$ grep -c "works:" *.yml | grep -v ":1" 
Biostar-TA790GX_A3+-Nukama.yml:2
Dell_Inc-Precision_WorkStation_T5500-20151217-155627.yml:2
Dell_Inc.-Latitude_E4300-Pablo_Costa.yml:2
Dell_Inc.-Latitude_E6420-marmarek.yml:4
Dell_Inc.-XPS_13-j.yml:3
Dell_Inc_-Inspiron_5423-20161122-115500.yml:2
Fujitsu-S751-Zrubi.yml:4
GIGABYTE-GA-870A-UD3-Fabian_Lichte.yml:2
HP-Compaq_dc7900_Convertible_Minitower-Nukama.yml:2
HP-Pavilion_Sleekbook_14-B030TU-Stephen_Boyd.yml:2
LENOVO-20HJS0BX00-20171215-110620.yml:2
LENOVO-2352CTO-20150825-203258.yml:2
Lenovo-ThinkPad_T420.yml:2
Lenovo-ThinkPad_T420s.yml:4
Lenovo-ThinkPad_T430s-cprise.yml:4
Lenovo-ThinkPad_T440p_(20AN00C1MD)-Bjarne_Thomsen.yml:2
Lenovo-ThinkPad_T510_(4384-WGZ)-pete.yml:2
Lenovo-ThinkPad_T61.yml:3
Lenovo-ThinkPad_X220_(4290-W3W).yml:3
Lenovo-ThinkPad_X230.yml:2
Qubes-HCL-LENOVO-20FQ005UGE-ypid.yml:3
Samsung-Series_7_Chronos_NP700Z5C-Outback_Dingo.yml:3
Samsung-X460-marmarek.yml:3
Sony-VAIO_Z_12_(2010_edition).yml:4
Sony-VAIO_series_Z2_2011_edition_(VPCZ2190S)-Danny_Fullerton.yml:2
Supermicro-X10SAE-Qubes_Fan.yml:2
[user@poder _hcl ((adw_9736641e))]$ grep -c "works:" *.yml | grep -v ":1" |wc -l
26
```

and only **3** with a >= 4.0 Qubes-OS version:
```
[user@poder _hcl ((adw_9736641e))]$ grep -c "works:" *.yml | grep -v ":1" | cut -d":" -f1 | xargs grep -A1 "qubes:" | grep -v -E "\-\-|qubes\:"| grep R4
Dell_Inc_-Inspiron_5423-20161122-115500.yml-    R4.0
LENOVO-20HJS0BX00-20171215-110620.yml-    R4.0
Qubes-HCL-LENOVO-20FQ005UGE-ypid.yml-    R4.0
```

Also, note that these **26** yml files use the old yml filename, without the `YYYYMMDD-HHMMSS` timestamp ID. So is it possible to get new yml files with multiple `-works` entries?

So before to try to solve the sort problem with `sorttable.js`, do you want to keep theses oldies ? Because a basic solution is to keep only the last `- works ` entry for these 26 yml files. But of course, I'll understand if you want to keep them for any reasons.

**Comment by lubellier** [comment]
`sorttable.js` with `td rowspan=` is a no-way, because `sorttable.js` doesn't support rowspan and colspan.

I see two ways:
1. replace `sorttable.js` with another library that supports rowspan : 
  a. The most known library is [DataTables](https://datatables.net/), which doesn't support rowspan ([source](https://datatables.net/manual/installation#HTML) )
  b. The second most known is [BootGrid](http://www.jquery-bootgrid.com/), the features list doesn't talk about rowspan ([source](http://www.jquery-bootgrid.com/GettingStarted))
  c. see other libraries...
2. keep `sorttable.js` but change the display of the table : 
  a. remove rowspan and display multiple lines (I tested it, the template change is simple, see the below screenshot).
  b. other ideas?

Table display without rowspan, replaced by multiple lines:
image

Can you share your preferences or ideas?

**Comment by andrewdavidwong** [comment]
I have no preference regarding the library. Multiple lines seems fine.

**Comment by andrewdavidwong** [comment]
I'm trying to merge this and #163, but the merge conflict here is really confusing. It says that `_doc` is the only conflicting file, but of course `_doc` is just the `qubes-doc` submodule. Of course, I want to use the version that is most recent in the `master` branch, but I'm not sure how to do that, because when I actually handle the merge conflict in git on the command line, I see no way to do anything besides simply `git add _doc`. I guess I will do that, since it's the only thing I can do, and hope it doesn't screw everything up. :slightly_frowning_face:

**Pull request merged**
