### PR TITLE
Update donation page

### PR DESCRIPTION
**Pull request by andrewdavidwong**
- Improve layout and formatting
- Add cryptocurrency donation address QR codes

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
TestDeploy

**Comment by andrewdavidwong** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRefresh

**Comment by andrewdavidwong** [comment]
TestDeploy

**Comment by andrewdavidwong** [comment]
TestDeploy

**Comment by andrewdavidwong** [comment]
TestDeploy

**Comment by andrewdavidwong** [comment]
PipelineRefresh

**Comment by andrewdavidwong** [comment]
TestDeploy

**Pull request merged**
