### PR TITLE
Fix mirror links

### PR DESCRIPTION
**Pull request by jpouellet**
Fixes https://github.com/QubesOS/qubes-issues/issues/2752

### CODE REVIEW

**Comment by jpouellet** [comment]
Resulting HTML diff: 
[html.diff.txt](https://github.com/QubesOS/qubesos.github.io/files/926886/html.diff.txt)

**Comment by jpouellet** [comment]
Before:
```
$ time htmlproofer ./_site --disable-external --checks-to-ignore ImageCheck --file-ignore ./_site/video-tours/index.html --url-ignore /qubes-issues/
Running ["ScriptCheck", "LinkCheck"] on ["./_site"] on *.html... 


Ran on 907 files!


- ./_site/downloads/index.html
  *  https://mirrors.kernel.org / is an invalid URL (line 343)
     <a href="https://mirrors.kernel.org%20/"><i class="fa fa-linux fa-fw black-icon"></i><samp> mirrors.kernel.org </samp></a>
  *  https://mirrors.kernel.org / is an invalid URL (line 502)
     <a href="https://mirrors.kernel.org%20/"><i class="fa fa-linux fa-fw black-icon"></i><samp> mirrors.kernel.org </samp></a>
htmlproofer 3.6.0 | Error:  HTML-Proofer found 2 failures!
```

After:
```
$ htmlproofer ./_site --disable-external --checks-to-ignore ImageCheck --file-ignore ./_site/video-tours/index.html --url-ignore /qubes-issues/
Running ["ScriptCheck", "LinkCheck"] on ["./_site"] on *.html... 


Ran on 907 files!


HTML-Proofer finished successfully.
```

**Comment by jpouellet** [comment]
There does not seem to be a suitable [template filter](https://jekyllrb.com/docs/templates/) to extract the name from the URLs.

**Comment by andrewdavidwong** [comment]
Nice, thanks!

**Pull request merged**
