### PR TITLE
Add link to Windows documentation

### PR DESCRIPTION
**Pull request by GWeck**

### CODE REVIEW

**Comment by GWeck** [comment]
Hope this link will work after my other pull request is executed. Please check!

**Comment by andrewdavidwong** [comment]
This link won't work, because you haven't opened a PR in qubes-doc that adds a page with the (relative) URL `/doc/templates/windows/`. All you've opened (so far) is https://github.com/QubesOS/qubes-doc/pull/1286, which (so far) only adds a section of text to an existing page.

**Comment by andrewdavidwong** [comment]
This PR is fine now. Just waiting for https://github.com/QubesOS/qubes-doc/pull/1286 to be merged first.

**Comment by marmarek** [comment]
Should this also drop the link from "external documentation" section? It already points at www.qubes-os.org anyway.

**Comment by andrewdavidwong** [comment]
> Should this also drop the link from "external documentation" section?

Yep, you're right.

> It already points at [www.qubes-os.org](http://www.qubes-os.org) anyway.

Not exactly. If you try clicking on the link, you'll see that there's actually a redirect in place that takes you to https://github.com/Qubes-Community/Contents/blob/master/docs/os/windows/windows.md.

**Comment by marmarek** [comment]
> If you try clicking on the link (on the live website right now), you'll see that there's actually a redirect in place that takes you to https://github.com/Qubes-Community/Contents/blob/master/docs/os/windows/windows.md.

I know, and then https://github.com/QubesOS/qubes-doc/pull/1286 removes the redirect (or rather: changes it to point at local page).

**Comment by andrewdavidwong** [comment]
> I know, and then [QubesOS/qubes-doc#1286](https://github.com/QubesOS/qubes-doc/pull/1286) removes the redirect (or rather: changes it to point at local page).

Right, that's why I agree with removing the Windows external link as part of the migration. It's useful and appropriate before the migration, but it won't be after the migration.

**Pull request merged**
