### PR TITLE
Use proper table class and transform release to a data file

### PR DESCRIPTION
**Pull request by Rudd-O**
This improves the look of the tables overall (right now none of the wiki can use tables because their text  is all bunched up together -- this fix resolves the issue without touching any of the SASS files).

Soon  I will have a proper download page to compare against the one we have now.

### CODE REVIEW

**Comment by bnvk** [comment]
@Rudd-O we're using the Bootstrap CSS framework, you just need to assign the right CSS classes, such as `<table class="table">` and then, as you can see the tables on [this page](https://www.qubes-os.org/compatible-hardware/), they look a bit better

**Comment by axon-qubes** [comment]
I should also point out that we currently have some decent-looking tables on certain pages, e.g. https://qubes-os.org/doc/supported-versions/

However, that's because we currently have this style block in the actual `.md` document (which we obviously want to (re)move in favor of a proper solution):
```
<style>
article td, article th {
    border-width: 2px;
    border-style: double;
    padding: 5px;
}
</style>
```

**Comment by bnvk** [comment]
@axon-qubes @Rudd-O yes, inline fragments of bespoke CSS throughout the site is what leads to very disorganized design that generally degrades over time. Add to the master stylesheets is the way to go!

That said, there are also limitations to what we can do with Markdown + Jeykll, which in turn limit what we can do with CSS. This is why I advocate (and started migrating things towards) using `data.yml` files and normal HTML for pages like the HCL and Team page, example:

- [team.yml](https://raw.githubusercontent.com/QubesOS/qubesos.github.io/master/_data/team.yml)
- [team.md](https://raw.githubusercontent.com/QubesOS/qubesos.github.io/master/pages/team.md)

This approach gives us lots of flexibility in terms of styling, but nice terse data, that still stored in version control :)

**Comment by axon-qubes** [comment]
That sounds like a great solution, @bnvk!

**Comment by axon-qubes** [comment]
What's the status of this PR, @Rudd-O?

**Comment by Rudd-O** [comment]
Picking it up right now.

**Comment by Rudd-O** [comment]
OK, I have upgraded it not to use any custom CSS, and to use a data file instead.  I will be updating the title of the pull request now.

**Comment by Rudd-O** [comment]
OK, this looks much better.

**Pull request merged**
