### PR TITLE
Sven: new fingerprint

### PR DESCRIPTION
**Pull request by SvenSemmler**
... transition to hardware based key (Nitrokey, internally generated key). Won't change again any time soon (years). Sorry.

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
It appears that your new key is not signed by your old key. Could you please post a message signed by your old key affirming that the new key is authentic?

**Comment by SvenSemmler** [comment]
> It appears that your new key is not signed by your old key. 

Sorry. I have done so now. The updated public key is here:

https://www.svensemmler.org/2A632C537D744BC7.asc

> Could you please post a message signed by your old key affirming that the new key is authentic?

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Starting May 29th 2021 I stopped using my the key with fingerprint D7CA 
F2DB 658D 89BC 08D6 A7AA DA6E 167B 8F54 1FB6 and started using the key 
with fingerprint DA59 75C9 ABC4 0C83 3B2F 620B 2A63 2C53 7D74 4BC7.
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEE18ry22WNibwI1qeq2m4We49UH7YFAmC0SCkACgkQ2m4We49U
H7bjaBAAhAkDdrSp5p0PDEPAVeaepmVF7azKwZcGyfLyGylvQrrNVm0fBgZd9UKL
UW50bADOIk2vzH5VZkY1kMevmdbFcG+bWbr5wFxTN6FENHbc9pFD2u9yIPALC4yj
kFcR9PVdHmGrcE6AFPjvidee0MkdZWT1yqafmt2h3qcyb5EVSw/HVrpsgyxQTUsP
Z/A/VVZdV7jzK2GwJ0tW9uGQiHV/oNoxbtIvrh7EF8T0C3T2txrzSzgRAmOtY4/3
b5v8fHXkbT+bP5TeI17nh4U37HdpN6ygcpECrf1xH+Iy9VlAZQnkXHr7mQ33S/MF
hZVWkg2LsJet3IbMyHKEP/kJK4tjQ7/wv5Zo8VKxdA77KeBFBO4M8geqISvpanEb
pHbW9+7bcay1NnSa1jJpPQY5+d2/xj8uUerd69lHAAeSunGMZqJqi1ztBwIYmXjq
lZAqVeorQh03l8EB1e3J6jc8QMaHkQndtl6KTOaOnC45TSaKvnTFCB4Ub3NUAKA2
7HLgrRD7OId2gyWryBMdlaB6gVE22Vrg4w0Tzc/zfJ2b6dfe4NA/IgKxnYK/kSGJ
ftDVSTZJa4oZlujcGojOZuO9G7QFJz19SMIrnVMa9CtBLc4F8wFNHhm2UNI5PJSn
jM9sC/nCjbJVnxwUHwMZhqUejG7K3qBDedBZa6btWfIHjI8Gpao=
=7iXv
-----END PGP SIGNATURE-----

**Comment by andrewdavidwong** [comment]
Thanks! I'm getting a bad signature on the message, but the new key is validly signed by the old key. Since either one is sufficient, I shall proceed.

**Comment by andrewdavidwong** [comment]
> Please click the three dots  as Github is collapsing the signed message for some reason.

I strongly recommend use code blocks or snippets for all formatting-sensitive text. (You can do that in Markdown by placing three backticks on a line both before and after the preformatted text.)

**Pull request merged**
