### PR TITLE
adding Demi to team page

### PR DESCRIPTION
**Pull request by mfc**
@marmarek @andrewdavidwong please add/edit more specific role.

photo (from github) merge request is here: https://github.com/QubesOS/qubes-attachment/pull/43

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
@DemiMarie, do you have any preference regarding your role description?

**Comment by DemiMarie** [comment]
@andrewdavidwong Would “software developer and security researcher” be good, or could it mislead people into thinking I am on the QubesOS Security Team?

**Comment by andrewdavidwong** [comment]
@DemiMarie: Typically, the description on this page refers more specifically to what one does on the Qubes OS Project, rather than a general description of the person's line of work. See the other descriptions for examples of this.

**Comment by marmarek** [comment]
What about "Software developer; Rust, Python"?

**Comment by DemiMarie** [comment]
> What about "Software developer; Rust, Python"?

That could work.  Perhaps also something to the effect of “Package management, GUI, and storage”?

**Comment by andrewdavidwong** [comment]
Updated. How does that look?

Please feel free to add commits to this PR.

**Review by DemiMarie — CHANGES_REQUESTED** [review]

**Review by DemiMarie — APPROVED** [review]

**Pull request merged**
